# Generated by Django 3.0.2 on 2020-02-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('img', models.ImageField(upload_to='page', verbose_name='Imagen')),
                ('content', models.TextField(verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'página',
            },
        ),
    ]
