# Generated by Django 3.0.2 on 2020-02-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200210_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_im_menu',
            field=models.BooleanField(default=True, verbose_name='Visible en el menú'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(help_text='Ingrese el nombre de la página', max_length=100, verbose_name='Nombre'),
        ),
    ]
