# Generated by Django 3.0.2 on 2020-02-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200210_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='show_im_menu',
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_footer',
            field=models.BooleanField(default=False, verbose_name='Visible en Footer'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_header',
            field=models.BooleanField(default=False, verbose_name='Visible en Header'),
        ),
    ]
