# Generated by Django 3.0.2 on 2020-02-12 13:42

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200210_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['name', 'order'], 'verbose_name': 'página'},
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='page',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='page', verbose_name='Imagen'),
        ),
    ]
