# Generated by Django 3.0.2 on 2020-02-09 02:46

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200207_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='blog', verbose_name='Imagen'),
        ),
    ]
